name: Typeset article
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TEXINPUTS: '.:./istqb_product_base/template:'
jobs:
  typeset-paper:
    name: Typeset article
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.6.2-5-g28fc6f72-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install additional packages
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends parallel zip
      - name: Typeset examples
        run: parallel --halt now,fail=1 -- latexmk -cd ':::' examples/*.tex
      - name: Typeset article
        run: latexmk tb140starynovotny-markdown-themes.ltx
      - name: Check that there are fewer than or exactly 10 pages
        run: test `tail tb140starynovotny-markdown-themes.log | sed -rn 's/.*\(([0-9]*) pages.*/\1/p'` -le 10
      - name: Archive sources
        run: zip -@ tb140starynovotny-markdown-themes < MANIFEST
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tb140starynovotny-markdown-themes
          path: tb140starynovotny-markdown-themes.zip
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            tb140starynovotny-markdown-themes.pdf
            tb140starynovotny-markdown-themes.zip
