name: Typeset article
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
  TEXINPUTS: '.:./istqb_product_base/template:'
jobs:
  typeset-paper:
    name: Typeset article
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install additional packages
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends parallel
      - name: Typeset examples
        run: parallel --halt now,fail=1 -- latexmk -cd ':::' examples/*.tex
      - name: Typeset article
        run: latexmk tb140starynovotny-markdown.ltx
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tb140starynovotny-markdown
          path: tb140starynovotny-markdown.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: tb140starynovotny-markdown.pdf
